'use strict'

export const ADD_NEW_USER = 'ADD_NEW_USER'
export const ADD_TO_USERS_LIST = 'ADD_TO_USERS_LIST'
export const CLEAR_USER = 'CLEAR_USER'
export const DELETE_USER = 'DELETE_USER'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USERS = 'FETCH_USERS'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_BY_ID = 'LOAD_USER_BY_ID'
export const LOAD_USERS = 'LOAD_USERS'
export const REMOVE_FROM_USERS_LIST = 'REMOVE_FROM_USERS_LIST'
export const SORT_FIRST_NAME = 'SORT_FIRST_NAME'
export const SORT_LAST_NAME = 'SORT_LAST_NAME'
export const SORT_LEVEL = 'SORT_LEVEL'
export const SORT_TYPE = 'SORT_TYPE'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_LEVEL = 'UPDATE_LEVEL'
export const UPDATE_NET_ID = 'UPDATE_NET_ID'
export const UPDATE_TYPE = 'UPDATE_TYPE'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST'
