'use strict'

export const FETCH_EDIT_USER = 'FETCH_EDIT_USER'
export const FETCH_USERS = 'FETCH_USERS'
export const LOAD_EDIT_USER = 'LOAD_EDIT_USER'
export const LOAD_USERS = 'LOAD_USERS'
export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_LEVEL = 'UPDATE_LEVEL'
export const UPDATE_NET_ID = 'UPDATE_NET_ID'
export const UPDATE_TYPE = 'UPDATE_TYPE'
